#!/bin/sh

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".php\{0,1\}$")

if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi

PASS=true

echo "\nValidating PHP-CS-FIXER:\n"

# Check for phpcs
which ./vendor/bin/php-cs-fixer &> /dev/null
if [[ "$?" == 1 ]]; then
  echo "\t\033[41mPlease install PHP-CS-FIXER\033[0m"
  exit 1
fi

for FILE in $STAGED_FILES
do
  ./vendor/bin/php-cs-fixer fix --dry-run "$FILE"

  if [[ "$?" == 0 ]]; then
    echo "\t\033[32m PHP-CS-FIXER Passed: $FILE\033[0m"
  else
    echo "\t\033[41m PHP-CS-FIXER Failed: $FILE\033[0m"
    PASS=false
  fi
done

echo "\nPHPCS validation completed!\n"

if ! $PASS; then
  echo "\033[41mCOMMIT FAILED:\033[0m Your commit contains files that should pass PHPCS but do not. Please fix the PHP-CS-FIXER errors and try again.\n"
  echo "\t\033[41m Run: composer lint \n"
  exit 1
else
  echo "\033[42mCOMMIT SUCCEEDED\033[0m\n"
fi

exit $?
